'use client';
import { useEffect, useRef, useState } from 'react';
import { loadProgress, saveProgress } from '@/services/progress/progress';
import type { PrecisionResult } from '../types';

export function StopAt100({ onBack }: { onBack: () => void }) { const [value, setValue] = useState(0); const [result, setResult] = useState<PrecisionResult | null>(null); const hold = useRef(false); const raf = useRef<number>();
  useEffect(() => { const tick = () => { if (hold.current && !result) setValue(v => Math.min(120, v + .34)); raf.current = requestAnimationFrame(tick); }; raf.current = requestAnimationFrame(tick); return () => { if (raf.current) cancelAnimationFrame(raf.current); }; }, [result]);
  const stop = () => { if (!hold.current || result) return; hold.current = false; const accuracy = Math.abs(100 - value); const score = Math.max(0, Math.round(1000 - accuracy * 35)); const next = { challengeId: 'stop-at-100', value, accuracy, score, passed: accuracy <= 5 }; setResult(next); if (score > loadProgress().precision.bestScore) saveProgress({ precision: { bestScore: score } }); };
  const reset = () => { hold.current = false; setValue(0); setResult(null); };
  const label = !result ? 'HOLD TO CHARGE' : result.accuracy < .5 ? 'PERFECT' : result.accuracy < 3 ? 'SO CLOSE' : result.accuracy < 8 ? 'GOOD' : 'TOO FAR';
  return <section className="mx-auto max-w-2xl px-1 pb-10 pt-14 sm:py-16"><p className="text-[10px] font-bold tracking-[.3em] text-fuchsia-300 sm:text-xs">STOP AT 100%</p><h1 className="mt-3 text-4xl font-black leading-tight sm:text-5xl">Freeze the meter.</h1><div className="mt-8 rounded-[1.75rem] border border-white/10 bg-white/[.04] p-5 shadow-2xl shadow-black/20 sm:mt-10 sm:rounded-3xl sm:p-10"><div className="flex items-end justify-between gap-3"><span className="text-xs text-white/50 sm:text-sm">CURRENT</span><span className="text-4xl font-black text-cyan-300 sm:text-5xl">{value.toFixed(2)}%</span></div><div className="mt-5 h-5 overflow-hidden rounded-full bg-black/60 sm:h-6"><div className="h-full rounded-full bg-gradient-to-r from-cyan-400 to-fuchsia-400 transition-[width]" style={{ width: `${Math.min(100, value / 1.2)}%` }} /><div className="relative -top-5 ml-[83.333%] h-5 w-0.5 bg-white sm:-top-6 sm:h-6" /></div><button onPointerDown={() => { if (!result) hold.current = true; }} onPointerUp={stop} onPointerLeave={stop} onPointerCancel={stop} className="mt-8 h-24 w-full rounded-2xl bg-cyan-300 text-base font-black text-black shadow-lg shadow-cyan-300/20 active:scale-[.99] sm:mt-10 sm:h-28 sm:text-lg">{result ? `STOPPED AT ${value.toFixed(2)}%` : label}</button>{result && <div className="mt-8 text-center"><p className="text-xs text-white/50 sm:text-sm">FEEDBACK</p><p className="mt-1 text-2xl font-black text-fuchsia-300 sm:text-3xl">{label}</p><p className="mt-3 text-sm text-white/60">Score {result.score} / 1000</p><button onClick={reset} className="mt-7 min-h-12 rounded-xl bg-white px-6 py-3 text-sm font-black text-black">TRY AGAIN</button></div>}</div><button onClick={onBack} className="mt-5 min-h-11 py-3 text-sm text-white/50">← BACK TO CHALLENGES</button></section>;
}
